[font]
size = 11

[font.normal]
family = "CaskaydiaCove Nerd Font"
style = "Light" 

[font.italic]
family = "VictorMono Nerd Font"
style = "Italic"

[font.bold]
family = "CaskaydiaCove Nerd Font"
style = "Regular"

[font.bold_italic]
family = "VictorMono Nerd Font"
style = "Bold Italic"
