[colors]
background = '#131313'
foreground = '#e2e2e2'

cursor_bg = '#b5c4ff'
cursor_fg = '#131313'
cursor_border = '#b5c4ff'

selection_bg = '#254190'
selection_fg = '#e2e2e2'

ansi = ['#131313', '#e44e45', '#6ed66f', '#dbd47b', '#6a7bda', '#929bbf', '#b5c4ff', '#abb2bf']
brights = ['#5c6370', '#e0625f', '#86e086', '#e8e297', '#c2d2ff', '#5978b4', '#7172b9', '#ffffff']
