[colors]
background = '#131313'
foreground = '#e2e2e2'

cursor_bg = '#afc6ff'
cursor_fg = '#131313'
cursor_border = '#afc6ff'

selection_bg = '#16448f'
selection_fg = '#e2e2e2'

ansi = ['#131313', '#e54d45', '#6fd66e', '#dbd37b', '#617ed1', '#8f9dbf', '#afc6ff', '#abb2bf']
brights = ['#5c6370', '#e0615f', '#86e086', '#e8e197', '#bbd4ff', '#547baf', '#6c75b4', '#ffffff']
