[colors.primary]
background = '#131313'
foreground = '#e2e2e2'

[colors.selection]
text = '#e2e2e2'
background = '#393d8f'

[colors.cursor]
text = '#131313'
cursor = '#bfc2ff'

[colors.normal]
black   = '#131313'
red     = '#e44f44'
green   = '#6ed670'
yellow  = '#dbd57b'
blue    = '#7775e6'
magenta = '#989abf'
cyan    = '#bfc2ff'
white   = '#abb2bf'

[colors.bright]
black   = '#5c6370'
red     = '#e0645f'
green   = '#86e088'
yellow  = '#e8e397'
blue    = '#cccfff'
magenta = '#6575c0'
cyan    = '#7870bc'
white   = '#ffffff'
