[colors.primary]
background = '#131313'
foreground = '#e2e2e2'

[colors.selection]
text = '#e2e2e2'
background = '#16448f'

[colors.cursor]
text = '#131313'
cursor = '#afc6ff'

[colors.normal]
black   = '#131313'
red     = '#e54d45'
green   = '#6fd66e'
yellow  = '#dbd37b'
blue    = '#617ed1'
magenta = '#8f9dbf'
cyan    = '#afc6ff'
white   = '#abb2bf'

[colors.bright]
black   = '#5c6370'
red     = '#e0615f'
green   = '#86e086'
yellow  = '#e8e197'
blue    = '#bbd4ff'
magenta = '#547baf'
cyan    = '#6c75b4'
white   = '#ffffff'
