[font]
size = 9

builtin_box_drawing = true
offset = { x = 0, y = 3 }

# normal = { family = "JetBrainsMono Nerd Font"
# bold = { family = "JetBrainsMono Nerd Font"
# italic = { family = "JetBrainsMono Nerd Font"
# bold_italic = { family = "JetBrainsMono Nerd Font"

normal = { family = "FiraCode Nerd Font" }
bold = { family = "FiraCode Nerd Font" }
italic = { family = "FiraCode Nerd Font" }
